/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package decorator;

public class Main {
    public static void main(String[] args) {
        // Cafe khong toping
        Beverage houseBlend = new HouseBlend();
        System.out.println(houseBlend.getDescription() + " non toping is " + houseBlend.cost());

        // Them mocha
        houseBlend = new Mocha(houseBlend);
        System.out.println(houseBlend.getDescription() + "'s price is " + houseBlend.cost());

        // Espresso
        Beverage espresso = new Espresso();
        System.out.println(espresso.getDescription() + "'s price is " + espresso.cost());

        // Them x2 Whip, mocha
        espresso = new Whip(espresso);
        espresso = new Whip(espresso);
        espresso = new Mocha(espresso);
        System.out.println(espresso.getDescription() + "'s price is " + espresso.cost());
    }
}
